from rest_framework import viewsets, status
from rest_framework.decorators import action
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated
from django.utils import timezone
from datetime import timedelta
from django.db.models import Q
from .models import IncidentTrend, SafetyMetrics, ComplianceReport, LocationStatistics
from .serializers import (
    IncidentTrendSerializer,
    SafetyMetricsSerializer,
    ComplianceReportSerializer,
    LocationStatisticsSerializer
)


class IncidentTrendViewSet(viewsets.ReadOnlyModelViewSet):
    """
    READ-ONLY ViewSet for incident trend analytics
    Data is auto-generated by apscheduler at midnight
    Users can only view trends, not create/edit/delete

    Provides filtering by period type and date range
    """
    queryset = IncidentTrend.objects.all()
    serializer_class = IncidentTrendSerializer
    permission_classes = [IsAuthenticated]

    def get_queryset(self):
        queryset = IncidentTrend.objects.all()

        # Filter by vessel
        vessel_id = self.request.query_params.get('vessel', None)
        if vessel_id:
            queryset = queryset.filter(vessel_id=vessel_id)

        # Filter by period type
        period_type = self.request.query_params.get('period_type', None)
        if period_type:
            queryset = queryset.filter(period_type=period_type)

        # Filter by date range
        start_date = self.request.query_params.get('start_date', None)
        end_date = self.request.query_params.get('end_date', None)

        if start_date:
            queryset = queryset.filter(period_start__gte=start_date)
        if end_date:
            queryset = queryset.filter(period_end__lte=end_date)

        return queryset.order_by('-period_start')

    @action(detail=False, methods=['get'])
    def latest(self, request):
        """
        Get latest trend for each period type
        """
        period_type = request.query_params.get('period_type', 'MONTHLY')

        latest_trend = IncidentTrend.objects.filter(
            period_type=period_type
        ).order_by('-period_start').first()

        if latest_trend:
            serializer = self.get_serializer(latest_trend)
            return Response(serializer.data)

        return Response(
            {'error': 'No trend data available'},
            status=status.HTTP_404_NOT_FOUND
        )

    @action(detail=False, methods=['get'])
    def summary(self, request):
        """
        Get summary statistics across all periods
        """
        period_type = request.query_params.get('period_type', 'MONTHLY')
        limit = int(request.query_params.get('limit', 12))

        trends = IncidentTrend.objects.filter(
            period_type=period_type
        ).order_by('-period_start')[:limit]

        serializer = self.get_serializer(trends, many=True)
        return Response(serializer.data)


class SafetyMetricsViewSet(viewsets.ReadOnlyModelViewSet):
    """
    READ-ONLY ViewSet for safety performance metrics
    Data is auto-generated by apscheduler at midnight
    Users can only view metrics, not create/edit/delete

    Provides daily/weekly/monthly safety statistics
    """
    queryset = SafetyMetrics.objects.all()
    serializer_class = SafetyMetricsSerializer
    permission_classes = [IsAuthenticated]

    def get_queryset(self):
        queryset = SafetyMetrics.objects.all()

        # Filter by vessel
        vessel_id = self.request.query_params.get('vessel', None)
        if vessel_id:
            queryset = queryset.filter(vessel_id=vessel_id)

        # Filter by date range
        start_date = self.request.query_params.get('start_date', None)
        end_date = self.request.query_params.get('end_date', None)

        if start_date:
            queryset = queryset.filter(date__gte=start_date)
        if end_date:
            queryset = queryset.filter(date__lte=end_date)

        # Filter by status
        global_status = self.request.query_params.get('status', None)
        if global_status:
            queryset = queryset.filter(global_status=global_status)

        return queryset.order_by('-date')

    @action(detail=False, methods=['get'])
    def latest(self, request):
        """
        Get latest safety metrics snapshot
        """
        latest_metrics = SafetyMetrics.objects.order_by('-date').first()

        if latest_metrics:
            serializer = self.get_serializer(latest_metrics)
            return Response(serializer.data)

        return Response(
            {'error': 'No metrics data available'},
            status=status.HTTP_404_NOT_FOUND
        )

    @action(detail=False, methods=['get'])
    def weekly_summary(self, request):
        """
        Get last 7 days of safety metrics
        """
        end_date = timezone.now().date()
        start_date = end_date - timedelta(days=7)

        metrics = SafetyMetrics.objects.filter(
            date__gte=start_date,
            date__lte=end_date
        ).order_by('-date')

        serializer = self.get_serializer(metrics, many=True)
        return Response(serializer.data)

    @action(detail=False, methods=['get'])
    def monthly_summary(self, request):
        """
        Get last 30 days of safety metrics
        """
        end_date = timezone.now().date()
        start_date = end_date - timedelta(days=30)

        metrics = SafetyMetrics.objects.filter(
            date__gte=start_date,
            date__lte=end_date
        ).order_by('-date')

        serializer = self.get_serializer(metrics, many=True)
        return Response(serializer.data)


class ComplianceReportViewSet(viewsets.ReadOnlyModelViewSet):
    """
    READ-ONLY ViewSet for ISO 45001 compliance reports
    Data is auto-generated by apscheduler at midnight
    Users can only view reports, not create/edit/delete

    Provides audit reports and compliance tracking
    """
    queryset = ComplianceReport.objects.all()
    serializer_class = ComplianceReportSerializer
    permission_classes = [IsAuthenticated]

    def get_queryset(self):
        queryset = ComplianceReport.objects.all()

        # Filter by vessel
        vessel_id = self.request.query_params.get('vessel', None)
        if vessel_id:
            queryset = queryset.filter(vessel_id=vessel_id)

        # Filter by report type
        report_type = self.request.query_params.get('report_type', None)
        if report_type:
            queryset = queryset.filter(report_type=report_type)

        # Filter by compliance status
        overall_status = self.request.query_params.get('status', None)
        if overall_status:
            queryset = queryset.filter(overall_status=overall_status)

        # Filter by date range
        start_date = self.request.query_params.get('start_date', None)
        end_date = self.request.query_params.get('end_date', None)

        if start_date:
            queryset = queryset.filter(report_date__gte=start_date)
        if end_date:
            queryset = queryset.filter(report_date__lte=end_date)

        return queryset.order_by('-report_date')

    @action(detail=False, methods=['get'])
    def latest(self, request):
        """
        Get latest compliance report
        """
        report_type = request.query_params.get('report_type', None)

        queryset = ComplianceReport.objects.all()
        if report_type:
            queryset = queryset.filter(report_type=report_type)

        latest_report = queryset.order_by('-report_date').first()

        if latest_report:
            serializer = self.get_serializer(latest_report)
            return Response(serializer.data)

        return Response(
            {'error': 'No compliance reports available'},
            status=status.HTTP_404_NOT_FOUND
        )

    @action(detail=False, methods=['get'])
    def compliance_summary(self, request):
        """
        Get compliance summary statistics
        """
        reports = ComplianceReport.objects.all()

        total_reports = reports.count()
        compliant = reports.filter(overall_status='COMPLIANT').count()
        partial = reports.filter(overall_status='PARTIAL').count()
        non_compliant = reports.filter(overall_status='NON_COMPLIANT').count()

        avg_score = 0
        if total_reports > 0:
            total_score = sum(r.compliance_score for r in reports)
            avg_score = total_score / total_reports

        return Response({
            'total_reports': total_reports,
            'compliant': compliant,
            'partial_compliant': partial,
            'non_compliant': non_compliant,
            'average_compliance_score': round(avg_score, 2)
        })


class LocationStatisticsViewSet(viewsets.ReadOnlyModelViewSet):
    """
    READ-ONLY ViewSet for location-based statistics
    Data is auto-generated by apscheduler at midnight
    Users can only view statistics, not create/edit/delete

    Provides hotspot analysis and location risk scoring
    """
    queryset = LocationStatistics.objects.all()
    serializer_class = LocationStatisticsSerializer
    permission_classes = [IsAuthenticated]

    def get_queryset(self):
        queryset = LocationStatistics.objects.all()

        # Filter by vessel
        vessel_id = self.request.query_params.get('vessel', None)
        if vessel_id:
            queryset = queryset.filter(vessel_id=vessel_id)

        # Filter by location name
        location_name = self.request.query_params.get('location', None)
        if location_name:
            queryset = queryset.filter(location_name__icontains=location_name)

        # Filter by date range
        start_date = self.request.query_params.get('start_date', None)
        end_date = self.request.query_params.get('end_date', None)

        if start_date:
            queryset = queryset.filter(date__gte=start_date)
        if end_date:
            queryset = queryset.filter(date__lte=end_date)

        return queryset.order_by('-date', 'location_name')

    @action(detail=False, methods=['get'])
    def hotspots(self, request):
        """
        Get high-risk locations (hotspots)
        """
        risk_threshold = float(request.query_params.get('threshold', 50.0))
        limit = int(request.query_params.get('limit', 10))

        # Get latest statistics for each location
        latest_date = LocationStatistics.objects.order_by('-date').first()
        if not latest_date:
            return Response([])

        hotspots = LocationStatistics.objects.filter(
            date=latest_date.date,
            risk_score__gte=risk_threshold
        ).order_by('-risk_score')[:limit]

        serializer = self.get_serializer(hotspots, many=True)
        return Response(serializer.data)

    @action(detail=False, methods=['get'])
    def location_trend(self, request):
        """
        Get trend for a specific location
        """
        location_name = request.query_params.get('location', None)
        if not location_name:
            return Response(
                {'error': 'location parameter is required'},
                status=status.HTTP_400_BAD_REQUEST
            )

        days = int(request.query_params.get('days', 30))
        end_date = timezone.now().date()
        start_date = end_date - timedelta(days=days)

        stats = LocationStatistics.objects.filter(
            location_name=location_name,
            date__gte=start_date,
            date__lte=end_date
        ).order_by('-date')

        serializer = self.get_serializer(stats, many=True)
        return Response(serializer.data)

    @action(detail=False, methods=['get'])
    def summary(self, request):
        """
        Get summary statistics for all locations
        """
        # Get latest date
        latest_date = LocationStatistics.objects.order_by('-date').first()
        if not latest_date:
            return Response([])

        stats = LocationStatistics.objects.filter(
            date=latest_date.date
        ).order_by('-risk_score')

        serializer = self.get_serializer(stats, many=True)
        return Response(serializer.data)
