<template>
  <Dialog :open="show" @update:open="(val) => !val && $emit('close')">
    <DialogContent class="sm:max-w-[600px] max-h-[90vh] overflow-visible">
      <DialogHeader>
        <DialogTitle>Submit PTW Request</DialogTitle>
        <DialogDescription>
          Fill in the Permit to Work details below. Click submit when complete.
        </DialogDescription>
      </DialogHeader>

      <form @submit.prevent="handleSubmit" class="space-y-4 py-4 max-h-[calc(90vh-120px)] overflow-y-auto">
          <div class="space-y-2">
              <Label for="permit_id">Permit ID <span class="text-red-500">*</span></Label>
              <Input id="permit_id" :model-value="formData.permit_id" type="text" placeholder="Will be generated by system" readonly class="bg-slate-100 cursor-not-allowed" />
          </div>
          <div class="space-y-2">
              <Label for="applicant">Applicant <span class="text-red-500">*</span></Label>
              <div v-if="props.userRole === 'Admin' || props.userRole === 'Safety Officer'" class="w-full">
                  <Popover v-model:open="openApplicant">
                      <PopoverTrigger as-child>
                          <Button
                              variant="outline"
                              role="combobox"
                              :aria-expanded="openApplicant"
                              class="w-full justify-between"
                          >
                              {{ selectedApplicantData ? selectedApplicantData.full_name + ' (' + selectedApplicantData.emp_id + ')' : "Select employee..." }}
                              <CheckIcon class="ml-2 h-4 w-4 shrink-0 opacity-50" />
                          </Button>
                      </PopoverTrigger>
                      <PopoverContent class="p-0 w-[550px]">
                          <Command>
                              <CommandInput placeholder="Search employee..." />
                              <CommandList>
                                  <CommandEmpty>No employee found.</CommandEmpty>
                                  <CommandGroup>
                                      <CommandItem
                                          v-for="emp in availableUsers"
                                          :key="emp.emp_id"
                                          :value="emp.emp_id"
                                          @select="(ev) => {
                                              selectedApplicant = ev.detail.value === selectedApplicant ? '' : ev.detail.value
                                              openApplicant = false
                                          }"
                                      >
                                          {{ emp.full_name }} ({{ emp.emp_id }})
                                          <CheckIcon
                                              :class="cn(
                                                  'ml-auto h-4 w-4',
                                                  selectedApplicant === emp.emp_id ? 'opacity-100' : 'opacity-0',
                                              )"
                                          />
                                      </CommandItem>
                                  </CommandGroup>
                              </CommandList>
                          </Command>
                      </PopoverContent>
                  </Popover>
              </div>
              <div v-else>
                  <Input id="applicant" :model-value="currentUserDisplay || props.username" type="text" required readonly class="bg-slate-100 cursor-not-allowed" />
              </div>
          </div>

          <div class="space-y-2">
              <Label>Assigned Crew <span class="text-red-500">*</span></Label>
              <Popover v-model:open="openCrew">
                  <PopoverTrigger as-child>
                      <Button variant="outline" role="combobox" :aria-expanded="openCrew" class="w-full justify-between">
                          {{ selectedCrew.length ? selectedCrew.length + ' personnel selected' : 'Select crew...' }}
                          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="ml-2 h-4 w-4 shrink-0 opacity-50"><polyline points="6 9 12 15 18 9"></polyline></svg>
                      </Button>
                  </PopoverTrigger>
                  <PopoverContent class="p-0 w-[550px]">
                      <Command>
                          <CommandInput placeholder="Search employee..." />
                          <CommandList>
                              <CommandEmpty>No employee found.</CommandEmpty>
                              <CommandGroup>
                                  <CommandItem
                                      v-for="emp in availableUsers"
                                      :key="emp.emp_id"
                                      :value="emp.emp_id"
                                      @select="() => toggleCrewSelection(emp.emp_id)"
                                  >
                                      {{ emp.full_name }} ({{ emp.emp_id }})
                                      <CheckIcon
                                          :class="cn(
                                              'ml-auto h-4 w-4',
                                              selectedCrew.includes(emp.emp_id) ? 'opacity-100' : 'opacity-0',
                                          )"
                                      />
                                  </CommandItem>
                              </CommandGroup>
                          </CommandList>
                      </Command>
                  </PopoverContent>
              </Popover>
          </div>

          <div class="space-y-2">
              <Label for="permit_type">Permit Type <span class="text-red-500">*</span></Label>
              <Select v-model="formData.permit_type">
                  <SelectTrigger class="w-full">
                      <SelectValue placeholder="Select type" />
                  </SelectTrigger>
                  <SelectContent class="w-full">
                      <SelectGroup>
                          <SelectItem value="HOT_WORK">Hot Work Permit</SelectItem>
                          <SelectItem value="CONFINED_SPACE">Confined Space Entry Permit</SelectItem>
                          <SelectItem value="WORKING_AT_HEIGHT">Working at Height Permit</SelectItem>
                          <SelectItem value="ISOLATION">Isolation Certificate</SelectItem>
                      </SelectGroup>
                  </SelectContent>
              </Select>
          </div>
          <div class="space-y-2">
              <Label for="location">Location <span class="text-red-500">*</span></Label>
              <Select v-model="formData.deck_location">
                  <SelectTrigger class="w-full">
                      <SelectValue placeholder="Select location" />
                  </SelectTrigger>
                  <SelectContent class="w-full">
                      <SelectGroup>
                          <SelectItem v-for="loc in filteredLocations" :key="loc.id" :value="String(loc.id)">
                              {{ loc.deck_name }}
                          </SelectItem>
                      </SelectGroup>
                  </SelectContent>
              </Select>
              <span v-if="isLocationFilteredByAsset" class="text-[10px] text-orange-600 dark:text-orange-400 font-medium flex items-center gap-1 mt-1">
                  <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="inline-block"><circle cx="12" cy="12" r="10"/><line x1="12" y1="16" x2="12" y2="12"/><line x1="12" y1="8" x2="12.01" y2="8"/></svg>
                  Locations filtered and auto-selected based on the work order's target asset.
              </span>
          </div>
          <div class="space-y-2">
              <Label for="wo_id">Work Order <span class="text-red-500">*</span></Label>
              <Popover v-model:open="openWorkOrder">
                  <PopoverTrigger as-child>
                      <Button
                          variant="outline"
                          role="combobox"
                          :aria-expanded="openWorkOrder"
                          class="w-full justify-between"
                      >
                          {{ selectedWorkOrderData ? selectedWorkOrderData.wo_id + ' - ' + truncateText(selectedWorkOrderData.description) : "Select work order..." }}
                          <CheckIcon class="ml-2 h-4 w-4 shrink-0 opacity-50" />
                      </Button>
                  </PopoverTrigger>
                  <PopoverContent class="p-0 w-[550px]">
                      <Command>
                          <CommandInput placeholder="Search work order..." />
                          <CommandList>
                              <CommandEmpty>No work order found.</CommandEmpty>
                              <CommandGroup>
                                  <CommandItem
                                      v-for="wo in workOrders"
                                      :key="wo.wo_id"
                                      :value="wo.wo_id"
                                      @select="(ev) => {
                                          selectedWorkOrder = ev.detail.value === selectedWorkOrder ? '' : ev.detail.value
                                          openWorkOrder = false
                                      }"
                                  >
                                      {{ wo.wo_id }} - {{ truncateText(wo.description, 40) }}
                                      <CheckIcon
                                          :class="cn(
                                              'ml-auto h-4 w-4',
                                              selectedWorkOrder === wo.wo_id ? 'opacity-100' : 'opacity-0',
                                          )"
                                      />
                                  </CommandItem>
                              </CommandGroup>
                          </CommandList>
                      </Command>
                  </PopoverContent>
              </Popover>
          </div>

          <DialogFooter class="pt-4">
              <Button type="button" variant="outline" @click="$emit('close')">Cancel</Button>
              <Button type="submit">Submit Request</Button>
          </DialogFooter>
      </form>
    </DialogContent>
  </Dialog>
</template>

<script setup>
import { ref, watch, onMounted, computed } from 'vue';
import { authState, getAccessToken } from '@/store/auth';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Button } from '@/components/ui/button';
import { Select, SelectContent, SelectGroup, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover';
import { Command, CommandEmpty, CommandGroup, CommandInput, CommandItem, CommandList } from '@/components/ui/command';
import { CheckIcon } from '@lucide/vue';
import { cn } from '@/lib/utils';

const props = defineProps({
    show: Boolean,
    username: String,
    userRole: String,
    lastPermitId: String
});

const emit = defineEmits(['close', 'submitPtw']);

const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || 'http://localhost:8989/api/v1';

// Data refs
const availableUsers = ref([]);
const workOrders = ref([]);
const locations = ref([]);
const openApplicant = ref(false);
const openWorkOrder = ref(false);
const openCrew = ref(false);
const selectedApplicant = ref('');
const selectedWorkOrder = ref('');
const selectedCrew = ref([]);

const toggleCrewSelection = (empId) => {
    if (selectedCrew.value.includes(empId)) {
        selectedCrew.value = selectedCrew.value.filter(id => id !== empId);
    } else {
        selectedCrew.value.push(empId);
    }
};

const selectedApplicantData = computed(() =>
  availableUsers.value.find(emp => emp.emp_id === selectedApplicant.value),
);

const selectedWorkOrderData = computed(() =>
  workOrders.value.find(wo => wo.wo_id === selectedWorkOrder.value),
);

const filteredLocations = computed(() => {
    if (!selectedWorkOrder.value) {
        return locations.value;
    }
    const selectedWO = workOrders.value.find(wo => wo.wo_id === selectedWorkOrder.value);
    if (selectedWO && selectedWO.asset_assigned_decks && selectedWO.asset_assigned_decks.length > 0) {
        return selectedWO.asset_assigned_decks;
    }
    return locations.value;
});

const isLocationFilteredByAsset = computed(() => {
    if (!selectedWorkOrder.value) return false;
    const selectedWO = workOrders.value.find(wo => wo.wo_id === selectedWorkOrder.value);
    return !!(selectedWO && selectedWO.asset_assigned_decks && selectedWO.asset_assigned_decks.length > 0);
});

watch(selectedWorkOrder, (newWoId) => {
    if (newWoId) {
        const selectedWO = workOrders.value.find(wo => wo.wo_id === newWoId);
        if (selectedWO && selectedWO.asset_assigned_decks && selectedWO.asset_assigned_decks.length > 0) {
            formData.value.deck_location = String(selectedWO.asset_assigned_decks[0].id);
        }
    }
});

const currentUserDisplay = computed(() => {
    const currentUser = availableUsers.value.find(emp => emp.emp_id === props.username);
    if (currentUser) {
        return `${currentUser.full_name} (${currentUser.emp_id})`;
    }
    return props.username;
});

const truncateText = (text, maxLength = 50) => {
    if (!text) return '';
    return text.length > maxLength ? text.substring(0, maxLength) + '...' : text;
};

const formData = ref({
    permit_id: '',
    emp_id: '',
    permit_type: 'HOT_WORK',
    wo_id: '',
    deck_location: '',
    vessel_id: authState.selectedVessel?.asset_id || authState.assignedVessel?.asset_id || '',
    status: 'PENDING'
});

const fetchEmployees = async () => {
    try {
        const vesselId = authState.selectedVessel?.asset_id || authState.assignedVessel?.asset_id;
        let url = `${API_BASE_URL}/hse/employees/`;
        if (vesselId) {
            url += `?vessel_id=${vesselId}`;
        }
        const response = await fetch(url, {
            headers: {
                'Authorization': `Bearer ${getAccessToken()}`
            }
        });
        if (!response.ok) {
            throw new Error(`HTTP error! status: ${response.status}`);
        }
        const data = await response.json();
        availableUsers.value = data.map(emp => ({
            emp_id: emp.emp_id,
            full_name: emp.full_name,
            job_role: emp.job_role
        }));
    } catch (error) {
        console.error('Failed to fetch employees:', error);
    }
};

const fetchWorkOrders = async () => {
    try {
        // Get vessel from authState
        const vesselId = authState.selectedVessel?.asset_id || authState.assignedVessel?.asset_id;

        if (!vesselId) {
            console.warn('No vessel assigned. Cannot fetch work orders.');
            workOrders.value = [];
            return;
        }

        // Fetch from Asset Module with vessel filter
        const response = await fetch(`${API_BASE_URL}/asset/workorders/?vessel_id=${vesselId}`, {
            headers: {
                'Authorization': `Bearer ${getAccessToken()}`
            }
        });
        if (!response.ok) {
            throw new Error(`HTTP error! status: ${response.status}`);
        }
        const data = await response.json();
        workOrders.value = data;
    } catch (error) {
        console.error('Failed to fetch work orders:', error);
        workOrders.value = [];
    }
};

const fetchLocations = async () => {
    try {
        // Get vessel from authState (assigned vessel for non-admin, selected vessel for admin)
        const vesselId = authState.selectedVessel?.asset_id || authState.assignedVessel?.asset_id;

        if (!vesselId) {
            console.warn('No vessel assigned. Cannot fetch locations.');
            locations.value = [];
            return;
        }

        const response = await fetch(`${API_BASE_URL}/offshore/locations/?vessel_id=${vesselId}`, {
            headers: {
                'Authorization': `Bearer ${getAccessToken()}`
            }
        });
        if (!response.ok) {
            throw new Error(`HTTP error! status: ${response.status}`);
        }
        const data = await response.json();
        locations.value = data;
    } catch (error) {
        console.error('Failed to fetch locations:', error);
        locations.value = [];
    }
};

onMounted(async () => {
    await fetchEmployees();
    await fetchWorkOrders();
    await fetchLocations();
});

const generateNextPermitId = () => {
    if (!props.lastPermitId) {
        return 'PTW-001';
    }
    const match = props.lastPermitId.match(/PTW-(\d+)/);
    if (match) {
        const lastNumber = parseInt(match[1], 10);
        const nextNumber = lastNumber + 1;
        return `PTW-${String(nextNumber).padStart(3, '0')}`;
    }
    return 'PTW-001';
};

const resetForm = () => {
    formData.value = {
        permit_id: '',
        emp_id: props.username,
        permit_type: 'HOT_WORK',
        wo_id: '',
        deck_location: '',
        vessel_id: authState.selectedVessel?.asset_id || authState.assignedVessel?.asset_id || '',
        status: 'PENDING'
    };
    selectedApplicant.value = '';
    selectedWorkOrder.value = '';
    selectedCrew.value = [];
    openApplicant.value = false;
    openWorkOrder.value = false;
    openCrew.value = false;
};

watch(() => props.show, (newVal) => {
    if (newVal) resetForm();
}, { immediate: true });

watch(() => props.lastPermitId, (newVal) => {
    resetForm();
});

// Watch for vessel changes and re-fetch work orders, locations, and crew
watch(() => authState.selectedVessel?.asset_id || authState.assignedVessel?.asset_id, (newVesselId) => {
    if (newVesselId) {
        formData.value.vessel_id = newVesselId;
        fetchLocations();
        fetchWorkOrders();
        fetchEmployees();
    }
});

const handleSubmit = () => {
    const payload = {
        permit_id: formData.value.permit_id,
        emp_id: props.userRole === 'Admin' || props.userRole === 'Safety Officer' ? selectedApplicant.value : props.username,
        permit_type: formData.value.permit_type,
        wo_id: selectedWorkOrder.value,
        deck_location: formData.value.deck_location ? parseInt(formData.value.deck_location) : null,
        vessel: authState.selectedVessel?.asset_id || authState.assignedVessel?.asset_id || '',
        assigned_personnel_ids: selectedCrew.value,
        status: 'PENDING'
    };
    emit('submitPtw', payload);
};
</script>
