# Generated by Django 5.2.4 on 2026-05-29 11:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('asset_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.CharField(default='50 Pax', max_length=50)),
                ('icon', models.CharField(default='fa-ship text-red-500', max_length=100)),
                ('status', models.CharField(choices=[('OPERATIONAL', 'Operational'), ('MAINTENANCE', 'Under Maintenance'), ('CRITICAL', 'Critical')], default='OPERATIONAL', max_length=50)),
                ('health_score', models.IntegerField(default=100)),
                ('last_inspected', models.DateField(auto_now=True)),
                ('vessel', models.ForeignKey(on_delete=models.CASCADE, related_name='assets', to='asset_module.vessel')),
                ('assigned_decks', models.ManyToManyField(blank=True, related_name='assigned_vessels', to='hse_pob.worklocation')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('item_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
                ('category', models.CharField(default='Spare Part', max_length=100)),
                ('current_stock', models.IntegerField(default=0)),
                ('minimum_stock', models.IntegerField(default=10)),
                ('asset_location', models.ForeignKey(blank=True, null=True, on_delete=models.CASCADE, related_name='inventory', to='asset_module.asset')),
            ],
        ),
        migrations.CreateModel(
            name='MachineryEquipment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('equipment_name', models.CharField(max_length=100)),
                ('equipment_type', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('installation_date', models.DateField()),
                ('operating_hours', models.IntegerField(default=0)),
                ('last_maintenance_date', models.DateField(blank=True, null=True)),
                ('maintenance_interval_hours', models.IntegerField(default=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vessel', models.ForeignKey(on_delete=models.CASCADE, related_name='machinery_equipment', to='asset_module.vessel')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceTask',
            fields=[
                ('task_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=50)),
                ('scheduled_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='PENDING', max_length=50)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('vessel', models.ForeignKey(blank=True, null=True, on_delete=models.CASCADE, related_name='maintenance_tasks', to='asset_module.vessel')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=models.CASCADE, related_name='maintenance_tasks', to='asset_module.machineryequipment')),
                ('wo_id', models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, related_name='maintenance_tasks', to='asset_module.workorder')),
            ],
        ),
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('part_name', models.CharField(max_length=100)),
                ('part_number', models.CharField(max_length=100, unique=True)),
                ('quantity_on_hand', models.IntegerField(default=0)),
                ('reorder_level', models.IntegerField(default=5)),
                ('supplier', models.CharField(blank=True, max_length=100, null=True)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vessel', models.ForeignKey(on_delete=models.CASCADE, related_name='spare_parts', to='asset_module.vessel')),
            ],
        ),
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vessel_name', models.CharField(max_length=100, unique=True)),
                ('vessel_type', models.CharField(max_length=100)),
                ('imo_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('operational_status', models.CharField(choices=[('OPERATIONAL', 'Operational'), ('MAINTENANCE', 'Under Maintenance'), ('CRITICAL', 'Critical'), ('INACTIVE', 'Inactive')], default='OPERATIONAL', max_length=50)),
                ('health_score', models.IntegerField(default=100)),
                ('last_inspected', models.DateField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('wo_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('created_by', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=50)),
                ('scheduled_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vessel', models.ForeignKey(on_delete=models.CASCADE, related_name='work_orders', to='asset_module.vessel')),
            ],
        ),
    ]
