# Generated by Django 5.2.4 on 2026-05-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_module', '0001_initial'),
        ('hse_pob', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vessel',
            name='assigned_decks',
            field=models.ManyToManyField(blank=True, related_name='vessels', to='hse_pob.worklocation'),
        ),
    ]
