# Generated by Django 5.2.4 on 2026-06-09 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_module', '0002_vessel_assigned_decks'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='asset_module.asset'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='machinery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='asset_module.machineryequipment'),
        ),
    ]
