# Generated by Django 5.2.4 on 2026-06-12 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_module', '0003_workorder_asset_workorder_machinery'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrderMaterial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_used', models.IntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('spare_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset_module.sparepart')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='asset_module.workorder')),
            ],
        ),
    ]
