# Generated by Django 5.2.4 on 2026-06-25 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_module', '0004_workordermaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparepart',
            name='quantity_reserved',
            field=models.IntegerField(default=0),
        ),
    ]
