# Generated by Django 5.2.4 on 2026-06-25 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_module', '0005_sparepart_quantity_reserved'),
        ('hr_module', '0003_alter_employee_roster_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_work_orders', to='hr_module.employee'),
        ),
    ]
