# Generated by Django 5.2.4 on 2026-06-25 02:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_module', '0006_workorder_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='current_temperature',
            field=models.DecimalField(decimal_places=2, default=45.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='asset',
            name='current_vibration',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='machineryequipment',
            name='current_temperature',
            field=models.DecimalField(decimal_places=2, default=45.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='machineryequipment',
            name='current_vibration',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=5),
        ),
        migrations.CreateModel(
            name='TelemetryLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vibration', models.DecimalField(decimal_places=2, max_digits=5)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_logs', to='asset_module.asset')),
                ('machinery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_logs', to='asset_module.machineryequipment')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
