# Generated by Django 5.2.4 on 2026-06-25 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_module', '0007_asset_current_temperature_asset_current_vibration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workordermaterial',
            name='spare_part',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='quantity_reserved',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='supplier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='vessel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='asset_module.vessel'),
        ),
        migrations.AddField(
            model_name='workordermaterial',
            name='inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset_module.inventoryitem'),
        ),
        migrations.DeleteModel(
            name='SparePart',
        ),
    ]
