# Generated by Django 5.2.4 on 2026-06-25 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_module', '0008_remove_workordermaterial_spare_part_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machineryequipment',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='machinery_equipment', to='asset_module.asset'),
        ),
    ]
