# Generated by Django 5.2.4 on 2026-06-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_module', '0009_machineryequipment_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('WAITING_REVIEW', 'Waiting Review'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=50),
        ),
    ]
