# Generated by Django 5.2.4 on 2026-06-25 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset_module', '0010_add_waiting_review_to_workorder_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='current_temperature',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='current_vibration',
        ),
    ]
