# Generated by Django 5.2.4 on 2026-05-29 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_role', models.CharField(default='Worker', max_length=100)),
                ('roster_status', models.CharField(choices=[('ONBOARD', 'On Board'), ('OFFBOARD', 'Off Board')], default='ONBOARD', max_length=20)),
                ('mcu_expiry', models.DateField(blank=True, null=True, verbose_name='MCU Expiry Date')),
                ('mcu_status', models.CharField(choices=[('PENDING', 'Pending'), ('FIT', 'Fit'), ('UNFIT', 'Unfit'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'user_profile',
            },
        ),
    ]
