# Generated by Django 5.2.4 on 2026-06-10 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='roster_status',
            field=models.CharField(choices=[('ONBOARD', 'On Board'), ('AVAILABLE', 'Available')], default='AVAILABLE', max_length=20),
        ),
    ]
