# Generated by Django 5.2.4 on 2026-05-29 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck_name', models.CharField(max_length=100, unique=True, verbose_name='Deck Name')),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=20)),
            ],
            options={
                'verbose_name': 'Deck Location',
                'verbose_name_plural': 'Deck Locations',
                'ordering': ['deck_name'],
            },
        ),
        migrations.CreateModel(
            name='POBLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=50, verbose_name='Employee ID')),
                ('action', models.CharField(choices=[('IN', 'Check In'), ('OUT', 'Check Out')], max_length=3, verbose_name='Action')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('deck_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hse_pob.worklocation', verbose_name='Deck Location')),
            ],
            options={
                'verbose_name': 'POB Log',
                'verbose_name_plural': 'POB Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
