# Generated by Django 5.2.4 on 2026-06-09 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hse_pob', '0001_initial'),
        ('hse_ptw', '0004_permittowork_assigned_personnel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poblog',
            name='ptw',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pob_logs', to='hse_ptw.permittowork'),
        ),
    ]
