# Generated by Django 5.2.4 on 2026-05-29 11:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asset_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('DAILY', 'Daily Compliance Check'), ('WEEKLY', 'Weekly Audit'), ('MONTHLY', 'Monthly Review'), ('QUARTERLY', 'Quarterly Assessment'), ('ANNUAL', 'Annual Audit')], max_length=20)),
                ('report_date', models.DateField(default=django.utils.timezone.now)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('overall_status', models.CharField(choices=[('COMPLIANT', 'Fully Compliant'), ('PARTIAL', 'Partially Compliant'), ('NON_COMPLIANT', 'Non-Compliant')], default='COMPLIANT', max_length=20)),
                ('compliance_score', models.FloatField(help_text='Compliance percentage (0-100)')),
                ('total_checks', models.IntegerField(default=0)),
                ('passed_checks', models.IntegerField(default=0)),
                ('failed_checks', models.IntegerField(default=0)),
                ('findings', models.TextField(blank=True, help_text='Audit findings and observations')),
                ('recommendations', models.TextField(blank=True, help_text='Recommendations for improvement')),
                ('auditor_name', models.CharField(max_length=100)),
                ('auditor_emp_id', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vessel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compliance_reports', to='asset_module.vessel')),
            ],
            options={
                'db_table': 'hse_compliance_reports',
                'ordering': ['-report_date'],
                'indexes': [models.Index(fields=['report_type', '-report_date'], name='hse_complia_report__fdbe60_idx')],
            },
        ),
        migrations.CreateModel(
            name='IncidentTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly')], max_length=20)),
                ('period_start', models.DateField(help_text='Start date of the period')),
                ('period_end', models.DateField(help_text='End date of the period')),
                ('safety_observation_count', models.IntegerField(default=0)),
                ('near_miss_count', models.IntegerField(default=0)),
                ('first_aid_count', models.IntegerField(default=0)),
                ('lti_count', models.IntegerField(default=0)),
                ('total_incidents', models.IntegerField(default=0)),
                ('days_without_lti', models.IntegerField(default=0)),
                ('average_response_time', models.FloatField(blank=True, help_text='Average time to close incidents (hours)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vessel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incident_trends', to='asset_module.vessel')),
            ],
            options={
                'db_table': 'hse_incident_trends',
                'ordering': ['-period_start'],
                'indexes': [models.Index(fields=['period_type', '-period_start'], name='hse_inciden_period__959b01_idx')],
                'unique_together': {('period_type', 'period_start', 'vessel')},
            },
        ),
        migrations.CreateModel(
            name='LocationStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_check_ins', models.IntegerField(default=0)),
                ('total_check_outs', models.IntegerField(default=0)),
                ('average_occupancy', models.FloatField(default=0, help_text='Average personnel count')),
                ('peak_occupancy', models.IntegerField(default=0)),
                ('total_incidents', models.IntegerField(default=0)),
                ('total_ptw_issued', models.IntegerField(default=0)),
                ('risk_score', models.FloatField(default=0, help_text='Calculated risk score (0-100)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vessel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='location_statistics', to='asset_module.vessel')),
            ],
            options={
                'db_table': 'hse_location_statistics',
                'ordering': ['-date', 'location_name'],
                'indexes': [models.Index(fields=['location_name', '-date'], name='hse_locatio_locatio_9c18da_idx')],
                'unique_together': {('location_name', 'date', 'vessel')},
            },
        ),
        migrations.CreateModel(
            name='SafetyMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of metrics snapshot')),
                ('total_pob', models.IntegerField(default=0, help_text='Total persons on board')),
                ('total_ptw_issued', models.IntegerField(default=0)),
                ('total_ptw_completed', models.IntegerField(default=0)),
                ('total_ptw_rejected', models.IntegerField(default=0)),
                ('average_ptw_duration', models.FloatField(blank=True, help_text='Average PTW duration (hours)', null=True)),
                ('days_without_lti', models.IntegerField(default=0)),
                ('near_misses_count', models.IntegerField(default=0)),
                ('total_incidents', models.IntegerField(default=0)),
                ('ltifr', models.FloatField(blank=True, help_text='Lost Time Injury Frequency Rate', null=True)),
                ('trifr', models.FloatField(blank=True, help_text='Total Recordable Injury Frequency Rate', null=True)),
                ('global_status', models.CharField(default='GREEN', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vessel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='safety_metrics', to='asset_module.vessel')),
            ],
            options={
                'db_table': 'hse_safety_metrics',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['-date'], name='hse_safety__date_f2fe85_idx')],
                'unique_together': {('date', 'vessel')},
            },
        ),
    ]
