# Generated by Django 5.2.4 on 2026-05-29 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asset_module', '0001_initial'),
        ('hse_ptw', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('discipline', models.CharField(default='Marine', max_length=100)),
                ('daily_rate', models.IntegerField(default=500000)),
                ('allowance_rate', models.IntegerField(default=300000)),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('cert_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('cert_type', models.CharField(max_length=100)),
                ('expiry_date', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='hse_ptw.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('location', models.CharField(default='Offshore Rig A', max_length=100)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rosters', to='hse_ptw.employee')),
                ('vessel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rosters', to='asset_module.vessel')),
            ],
        ),
        migrations.CreateModel(
            name='VesselActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('activity_name', models.CharField(max_length=200)),
                ('vessel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='asset_module.vessel')),
            ],
        ),
    ]
