# Generated by Django 5.2.4 on 2026-06-09 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_module', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='Employee',
                    fields=[
                        ('emp_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                        ('full_name', models.CharField(max_length=100)),
                        ('job_role', models.CharField(max_length=100)),
                        ('roster_status', models.CharField(choices=[('ONBOARD', 'On Board'), ('OFFBOARD', 'Off Board')], max_length=50)),
                        ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                        ('mcu_expiry', models.DateField(blank=True, null=True)),
                        ('mcu_status', models.CharField(default='PENDING', max_length=50)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                    ],
                    options={
                        'db_table': 'hse_ptw_employee',
                    },
                ),
            ]
        ),
        migrations.AlterField(
            model_name='certification',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='hr_module.employee'),
        ),
        migrations.AlterField(
            model_name='roster',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rosters', to='hr_module.employee'),
        ),
    ]
