# Generated by Django 5.2.4 on 2026-06-10 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_module', '0002_employee_alter_certification_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='roster_status',
            field=models.CharField(choices=[('ONBOARD', 'On Board'), ('AVAILABLE', 'Available')], max_length=50),
        ),
    ]
