# Generated by Django 5.2.4 on 2026-05-29 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asset_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('job_role', models.CharField(max_length=100)),
                ('roster_status', models.CharField(choices=[('ONBOARD', 'On Board'), ('OFFBOARD', 'Off Board')], max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('mcu_expiry', models.DateField(blank=True, null=True)),
                ('mcu_status', models.CharField(default='PENDING', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PermitToWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_id', models.CharField(help_text='Format: HW-270526-0001', max_length=20, unique=True)),
                ('emp_id', models.CharField(max_length=50, verbose_name='Employee ID')),
                ('deck_location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Work Location')),
                ('permit_type', models.CharField(choices=[('HOT_WORK', 'Hot Work Permit'), ('CONFINED_SPACE', 'Confined Space Entry Permit'), ('WORKING_AT_HEIGHT', 'Working at Height Permit'), ('ISOLATION', 'Isolation Certificate')], max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved (Active)'), ('WAITING_FOR_CLOSE', 'Waiting for Close'), ('CLOSED', 'Closed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Safety Officer')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('signature', models.TextField(blank=True, help_text='Digital signature base64', null=True)),
                ('rejected_by', models.CharField(blank=True, max_length=100, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('completion_notes', models.TextField(blank=True, null=True)),
                ('closed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closing_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ptws', to='asset_module.vessel')),
                ('wo_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ptws', to='asset_module.workorder', verbose_name='Work Order')),
            ],
        ),
    ]
