# Generated by Django 5.2.4 on 2026-06-09 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hse_ptw', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permittowork',
            name='is_toolbox_talk_done',
            field=models.BooleanField(default=False),
        ),
    ]
