# Generated by Django 5.2.4 on 2026-06-09 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hse_pob', '0001_initial'),
        ('hse_ptw', '0002_permittowork_is_toolbox_talk_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permittowork',
            name='deck_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ptws', to='hse_pob.worklocation', verbose_name='Work Location'),
        ),
    ]
