# Generated by Django 5.2.4 on 2026-06-09 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hse_ptw', '0003_alter_permittowork_deck_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='permittowork',
            name='assigned_personnel',
            field=models.ManyToManyField(blank=True, related_name='assigned_ptws', to='hse_ptw.employee', verbose_name='Assigned Crew'),
        ),
        migrations.AlterField(
            model_name='permittowork',
            name='emp_id',
            field=models.CharField(max_length=50, verbose_name='Applicant ID'),
        ),
    ]
