# Generated by Django 5.2.4 on 2026-06-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_module', '0002_employee_alter_certification_employee_and_more'),
        ('hse_ptw', '0004_permittowork_assigned_personnel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permittowork',
            name='assigned_personnel',
            field=models.ManyToManyField(blank=True, related_name='assigned_ptws', to='hr_module.employee', verbose_name='Assigned Crew'),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(
                    name='Employee',
                ),
            ]
        ),
    ]
