# Generated by Django 5.2.4 on 2026-06-23 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hse_ptw', '0005_delete_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permittowork',
            name='jsa_loto_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permittowork',
            name='jsa_ppe_checked',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='permittowork',
            name='tbt_photo',
            field=models.ImageField(blank=True, null=True, upload_to='tbt_photos/'),
        ),
        migrations.AddField(
            model_name='permittowork',
            name='tbt_signatures',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
