# Generated by Django 5.2.4 on 2026-05-29 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asset_module', '0001_initial'),
        ('hse_pob', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusOverride',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('previous_status', models.CharField(choices=[('GREEN', 'Condition Green - All Safe'), ('YELLOW', 'Condition Yellow - Warning'), ('RED', 'Condition Red - Emergency')], max_length=10)),
                ('new_status', models.CharField(choices=[('GREEN', 'Condition Green - All Safe'), ('YELLOW', 'Condition Yellow - Warning'), ('RED', 'Condition Red - Emergency')], max_length=10)),
                ('override_reason', models.TextField(help_text='Reason for manual override')),
                ('changed_by', models.CharField(help_text='EMP ID of Safety Officer', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'hse_status_overrides',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('global_status', models.CharField(choices=[('GREEN', 'Condition Green'), ('YELLOW', 'Condition Yellow'), ('RED', 'Condition Red')], default='GREEN', max_length=10)),
                ('days_without_lti', models.IntegerField(default=0)),
                ('last_lti_date', models.DateField(blank=True, null=True)),
                ('near_misses_count', models.IntegerField(default=0)),
                ('active_permits', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_incident_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hse_system_status',
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('incident_id', models.CharField(blank=True, editable=False, help_text='Auto-generated incident ID based on severity', max_length=50, null=True, unique=True)),
                ('severity', models.CharField(choices=[('SAFETY_OBSERVATION', 'Safety Observation'), ('NEAR_MISS', 'Near Miss'), ('FIRST_AID', 'First Aid / Minor Injury'), ('LTI', 'LTI / Major Injury')], help_text='Incident severity level - KEY for metrics update', max_length=20)),
                ('description', models.TextField(help_text='Detailed incident description')),
                ('proof_image', models.ImageField(blank=True, help_text='Incident proof image', null=True, upload_to='incident_proofs/%Y/%m/%d/')),
                ('employee_name', models.CharField(blank=True, max_length=100, null=True)),
                ('reported_by', models.CharField(max_length=50)),
                ('incident_date', models.DateTimeField(help_text='When incident occurred')),
                ('reported_date', models.DateTimeField(auto_now_add=True, help_text='When reported')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING_VERIFICATION', 'Pending Verification'), ('OPEN', 'Open'), ('INVESTIGATING', 'Investigating'), ('CLOSED', 'Closed'), ('REJECTED', 'Rejected')], default='OPEN', max_length=20)),
                ('investigation_notes', models.TextField(blank=True, null=True)),
                ('closed_by', models.CharField(blank=True, max_length=50, null=True)),
                ('closed_date', models.DateTimeField(blank=True, null=True)),
                ('verified_by', models.CharField(blank=True, help_text='EMP ID of verifier', max_length=50, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason if rejected', null=True)),
                ('location', models.ForeignKey(help_text='Work location where incident occurred', on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='hse_pob.worklocation')),
                ('vessel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='asset_module.vessel')),
            ],
            options={
                'db_table': 'hse_incidents',
                'ordering': ['-incident_date'],
                'indexes': [models.Index(fields=['severity', '-incident_date'], name='hse_inciden_severit_8a7323_idx'), models.Index(fields=['status', '-created_at'], name='hse_inciden_status_35a412_idx')],
            },
        ),
    ]
